# Generated by Django 2.0.3 on 2018-08-04 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_auto_20180804_0028'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('county', models.CharField(max_length=100)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.StaffUser')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('price', models.IntegerField()),
                ('location', models.CharField(max_length=1000)),
                ('rating', models.IntegerField()),
                ('age_range', models.CharField(max_length=12)),
                ('skill_level', models.CharField(choices=[('ALL', 'ALL'), ('BEG', 'Beginner'), ('MID', 'Mid Level'), ('HGH', 'High Level')], default='ALL', max_length=3)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinics.Clinic')),
            ],
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='clinic',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinics.Sport'),
        ),
    ]
