# Generated by Django 2.0.3 on 2018-07-26 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='clinic',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinics.Sport'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='staff',
            field=models.ManyToManyField(to='users.UserProfile'),
        ),
    ]
